<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Model;

use CanadaPost\Model\Base\CanadaPostService as BaseCanadaPostService;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class CanadaPostService
 * @package CanadaPost\Model
 */
class CanadaPostService extends BaseCanadaPostService
{
    use ModelEventDispatcherTrait;
}
