<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Model;

use CanadaPost\Model\Base\CanadaPostServiceI18n as BaseCanadaPostServiceI18n;

/**
 * Class CanadaPostServiceI18n
 * @package CanadaPost\Model
 */
class CanadaPostServiceI18n extends BaseCanadaPostServiceI18n
{
}
