<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Model;

use CanadaPost\Model\Base\CanadaPostOrder as BaseCanadaPostOrder;

/**
 * Class CanadaPostOrder
 * @package CanadaPost\Model
 */
class CanadaPostOrder extends BaseCanadaPostOrder
{
}
