<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Action;

use CanadaPost\Action\Base\CanadaPostServiceAction as  BaseCanadaPostServiceAction;

/**
 * Class CanadaPostServiceAction
 * @package CanadaPost\Action
 */
class CanadaPostServiceAction extends BaseCanadaPostServiceAction
{
}
