<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Action;

use CanadaPost\Action\Base\CanadaPostOrderAction as  BaseCanadaPostOrderAction;

/**
 * Class CanadaPostOrderAction
 * @package CanadaPost\Action
 */
class CanadaPostOrderAction extends BaseCanadaPostOrderAction
{
}
