<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form\Type;

use CanadaPost\Form\Type\Base\CanadaPostServiceIdType as BaseCanadaPostServiceIdType;

/**
 * Class CanadaPostService
 * @package CanadaPost\Form
 */
class CanadaPostServiceIdType extends BaseCanadaPostServiceIdType
{
}
