<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form\Type;

use CanadaPost\Form\Type\Base\CanadaPostOrderIdType as BaseCanadaPostOrderIdType;

/**
 * Class CanadaPostOrder
 * @package CanadaPost\Form
 */
class CanadaPostOrderIdType extends BaseCanadaPostOrderIdType
{
}
