<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event;

use CanadaPost\Event\Base\CanadaPostEvents as BaseCanadaPostEvents;

/**
 * Class CanadaPostEvents
 * @package CanadaPost\Event
 * @author TheliaStudio
 */
class CanadaPostEvents extends BaseCanadaPostEvents
{
}
