<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event;

use CanadaPost\Event\Base\CanadaPostServiceEvents as BaseCanadaPostServiceEvents;

/**
 * Class CanadaPostServiceEvents
 * @package CanadaPost\Event
 */
class CanadaPostServiceEvents extends BaseCanadaPostServiceEvents
{
}
