<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event;

use CanadaPost\Event\Base\CanadaPostOrderEvent as BaseCanadaPostOrderEvent;

/**
 * Class CanadaPostOrderEvent
 * @package CanadaPost\Event
 */
class CanadaPostOrderEvent extends BaseCanadaPostOrderEvent
{
}
