<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event;

use CanadaPost\Event\Base\CanadaPostServiceEvent as BaseCanadaPostServiceEvent;

/**
 * Class CanadaPostServiceEvent
 * @package CanadaPost\Event
 */
class CanadaPostServiceEvent extends BaseCanadaPostServiceEvent
{
}
