<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event;

use CanadaPost\Event\Base\CanadaPostOrderEvents as BaseCanadaPostOrderEvents;

/**
 * Class CanadaPostOrderEvents
 * @package CanadaPost\Event
 */
class CanadaPostOrderEvents extends BaseCanadaPostOrderEvents
{
}
