<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form\Base;

use CanadaPost\Form\CanadaPostServiceCreateForm as ChildCanadaPostServiceCreateForm;
use CanadaPost\Form\Type\CanadaPostServiceIdType;

/**
 * Class CanadaPostServiceForm
 * @package CanadaPost\Form
 * @author TheliaStudio
 */
class CanadaPostServiceUpdateForm extends ChildCanadaPostServiceCreateForm
{
    const FORM_NAME = "canada_post_service_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", CanadaPostServiceIdType::TYPE_NAME)
            ->remove("visible")
        ;
    }
}
