<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form\Base;

use CanadaPost\CanadaPost;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class CanadaPostOrderCreateForm
 * @package CanadaPost\Form\Base
 * @author TheliaStudio
 */
class CanadaPostOrderCreateForm extends BaseForm
{
    const FORM_NAME = "canada_post_order_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addAddressIdField($translationKeys, $fieldsIdKeys);
        $this->addOrderAddressIdField($translationKeys, $fieldsIdKeys);
        $this->addServiceIdField($translationKeys, $fieldsIdKeys);
        $this->addOptionsField($translationKeys, $fieldsIdKeys);
    }

    protected function addAddressIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("address_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("address_id", $translationKeys), [], CanadaPost::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("address_id", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addOrderAddressIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("order_address_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("order_address_id", $translationKeys), [], CanadaPost::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("order_address_id", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addServiceIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("service_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("service_id", $translationKeys), [], CanadaPost::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("service_id", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addOptionsField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("options", "text", array(
            "label" => $this->translator->trans($this->readKey("options", $translationKeys), [], CanadaPost::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("options", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "address_id" => "canada_post_order_address_id",
            "order_address_id" => "canada_post_order_order_address_id",
            "service_id" => "canada_post_order_service_id",
            "options" => "canada_post_order_options",
        );
    }
}
