<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Loop;

use CanadaPost\Loop\Base\CanadaPostService as BaseCanadaPostServiceLoop;

/**
 * Class CanadaPostService
 * @package CanadaPost\Loop
 */
class CanadaPostService extends BaseCanadaPostServiceLoop
{
    /**
     * You may now add your own logic
     */
}
