<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Loop;

use CanadaPost\Loop\Base\CanadaPostOrder as BaseCanadaPostOrderLoop;

/**
 * Class CanadaPostOrder
 * @package CanadaPost\Loop
 */
class CanadaPostOrder extends BaseCanadaPostOrderLoop
{
    /**
     * You may now add your own logic
     */
}
