<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form;

use CanadaPost\Form\Base\CanadaPostServiceCreateForm as BaseCanadaPostServiceCreateForm;

/**
 * Class CanadaPostServiceCreateForm
 * @package CanadaPost\Form
 */
class CanadaPostServiceCreateForm extends BaseCanadaPostServiceCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "code" => "Code",
            "title" => "Title",
            "chapo" => "Chapo",
        );
    }
}
