<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form;

use CanadaPost\Form\Base\CanadaPostOrderUpdateForm as BaseCanadaPostOrderUpdateForm;

/**
 * Class CanadaPostOrderUpdateForm
 * @package CanadaPost\Form
 */
class CanadaPostOrderUpdateForm extends BaseCanadaPostOrderUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "address_id" => "address_id",
            "order_address_id" => "order_address_id",
            "service_id" => "service_id",
            "options" => "options",
        );
    }
}
