<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form;

use CanadaPost\Form\Base\CanadaPostOrderCreateForm as BaseCanadaPostOrderCreateForm;

/**
 * Class CanadaPostOrderCreateForm
 * @package CanadaPost\Form
 */
class CanadaPostOrderCreateForm extends BaseCanadaPostOrderCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "address_id" => "Address id",
            "order_address_id" => "Order address id",
            "service_id" => "Service id",
            "options" => "Options",
        );
    }
}
