<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form;

use CanadaPost\Form\Base\CanadaPostServiceUpdateForm as BaseCanadaPostServiceUpdateForm;

/**
 * Class CanadaPostServiceUpdateForm
 * @package CanadaPost\Form
 */
class CanadaPostServiceUpdateForm extends BaseCanadaPostServiceUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "code" => "code",
            "title" => "title",
            "chapo" => "chapo",
        );
    }
}
