<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event\Base;

/**
 * Class CanadaPostEvents
 * @package CanadaPost\Event\Base
 * @author TheliaStudio
 */
class CanadaPostEvents
{
    const CANADA_POST_ORDER_CREATE = "action.canada_post_order.create";
    const CANADA_POST_ORDER_UPDATE = "action.canada_post_order.update";
    const CANADA_POST_ORDER_DELETE = "action.canada_post_order.delete";
    const CANADA_POST_SERVICE_CREATE = "action.canada_post_service.create";
    const CANADA_POST_SERVICE_UPDATE = "action.canada_post_service.update";
    const CANADA_POST_SERVICE_DELETE = "action.canada_post_service.delete";
    const CANADA_POST_SERVICE_TOGGLE_VISIBILITY = "action.canada_post_service.toggle_visilibity";
}
