<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event\Base;

/**
 * Class CanadaPostEvents
 * @package CanadaPost\Event\Base
 * @author TheliaStudio
 */
class CanadaPostEvents
{
}
