<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event\Base;

use Thelia\Core\Event\ActionEvent;
use CanadaPost\Model\CanadaPostOrder;

/**
* Class CanadaPostOrderEvent
* @package CanadaPost\Event\Base
* @author TheliaStudio
*/
class CanadaPostOrderEvent extends ActionEvent
{
    protected $id;
    protected $addressId;
    protected $orderAddressId;
    protected $serviceId;
    protected $options;
    protected $canadaPostOrder;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getAddressId()
    {
        return $this->addressId;
    }

    public function setAddressId($addressId)
    {
        $this->addressId = $addressId;

        return $this;
    }

    public function getOrderAddressId()
    {
        return $this->orderAddressId;
    }

    public function setOrderAddressId($orderAddressId)
    {
        $this->orderAddressId = $orderAddressId;

        return $this;
    }

    public function getServiceId()
    {
        return $this->serviceId;
    }

    public function setServiceId($serviceId)
    {
        $this->serviceId = $serviceId;

        return $this;
    }

    public function getOptions()
    {
        return $this->options;
    }

    public function setOptions($options)
    {
        $this->options = $options;

        return $this;
    }

    public function getCanadaPostOrder()
    {
        return $this->canadaPostOrder;
    }

    public function setCanadaPostOrder(CanadaPostOrder $canadaPostOrder)
    {
        $this->canadaPostOrder = $canadaPostOrder;

        return $this;
    }
}
