<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event\Base;

use CanadaPost\Event\CanadaPostEvents as ChildCanadaPostEvents;

/*
 * Class CanadaPostOrderEvents
 * @package CanadaPost\Event\Base
 * @author TheliaStudio
 */
class CanadaPostOrderEvents
{
    const CREATE = ChildCanadaPostEvents::CANADA_POST_ORDER_CREATE;
    const UPDATE = ChildCanadaPostEvents::CANADA_POST_ORDER_UPDATE;
    const DELETE = ChildCanadaPostEvents::CANADA_POST_ORDER_DELETE;
}
