<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Event\Base;

use Thelia\Core\Event\ActionEvent;
use CanadaPost\Model\CanadaPostService;

/**
* Class CanadaPostServiceEvent
* @package CanadaPost\Event\Base
* @author TheliaStudio
*/
class CanadaPostServiceEvent extends ActionEvent
{
    protected $id;
    protected $visible;
    protected $code;
    protected $title;
    protected $chapo;
    protected $canadaPostService;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getVisible()
    {
        return $this->visible;
    }

    public function setVisible($visible)
    {
        $this->visible = $visible;

        return $this;
    }

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getChapo()
    {
        return $this->chapo;
    }

    public function setChapo($chapo)
    {
        $this->chapo = $chapo;

        return $this;
    }

    public function getCanadaPostService()
    {
        return $this->canadaPostService;
    }

    public function setCanadaPostService(CanadaPostService $canadaPostService)
    {
        $this->canadaPostService = $canadaPostService;

        return $this;
    }
}
