<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use CanadaPost\Model\CanadaPostServiceQuery;

/**
 * Class CanadaPostService
 * @package CanadaPost\Form\Base
 * @author TheliaStudio
 */
class CanadaPostServiceIdType extends AbstractIdType
{
    const TYPE_NAME = "canada_post_service_id";

    protected function getQuery()
    {
        return new CanadaPostServiceQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
