<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Controller;

use CanadaPost\Controller\Base\CanadaPostConfigController as BaseCanadaPostConfigController;

/**
 * Class CanadaPostConfigController
 * @package CanadaPost\Controller
 */
class CanadaPostConfigController extends BaseCanadaPostConfigController
{
}
