<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CanadaPost\Controller;

use CanadaPost\Controller\Base\CanadaPostOrderController as BaseCanadaPostOrderController;

/**
 * Class CanadaPostOrderController
 * @package CanadaPost\Controller
 */
class CanadaPostOrderController extends BaseCanadaPostOrderController
{
}
